<template>
  <div class="text">
    <div v-if="isLoggedIn">
      <img :src=user.avatar_url alt="" width="100" style="border-radius: 50px"/>
      <div>{{user.name}}</div>
    </div>
    <a v-else
       href="#"
       @click="login">请登录</a>
  </div>
</template>

<script>
import { Component, Vue } from 'vue-property-decorator';
import GitHub from 'github-api';

@Component
export default class Sidebar extends Vue {
    isLoggedIn = false;

    user = {};

    mounted() {
      const accessToken = localStorage.getItem('access_token');
      if (!accessToken) return;
      const gh = new GitHub({ token: accessToken });
      const user = gh.getUser();
      user.getProfile().then((userRes) => {
        this.user = userRes.data;
        this.isLoggedIn = true;
        gh.getRepo(this.user.login, 'geekmd-files')
          .getDetails()
          .catch((e) => {
            if (e.response.status === 404) {
              user.createRepo({
                name: 'geekmd-files',
                description: 'Files generated by GeekMD',
                private: true,
              });
              // .then(data => console.log(data));
              // console.error(JSON.parse(JSON.stringify(e.response.status)));
            }
          });

        // if () {}
      }).catch(() => {
        this.isLoggedIn = false;
      });
    }

    login() {
      const width = 360;
      const height = 600;
      const top = (window.screen.availHeight - 30 - height) / 2;
      const left = (window.screen.availWidth - 10 - width) / 2;
      window.open('https://github.com/login/oauth/authorize?client_id=2716d2180d1a362bf08a&scope=repo&redirect_uri=https://md.wangbaiyuan.cn/auth', 'newwindow', `height=${height}, width=${width}, top=${top}, left=${left}, toolbar=no, menubar=no, scrollbars=no, resizable=no,location=no, status=no, titlebar=no`);
    }
}

</script>

<style scoped>

</style>
